name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm run build
      - name: Run tests      
        run: cucumber-js features/