name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install typescript -g
      - run: npm install tsc --prefix /src
      - run: yarn --prefix /src
      - run: npm install --prefix /src
      - run: npm run test  --prefix /src   